#!/usr/bin/env Rscript
randata=runif(10,-1,1)
x=c(1:10)
y=2*x+3*(randata/2)
mx=matrix(c(x,y),ncol=2)
df=as.data.frame(mx)
colnames(df)=c('X','Y')
plot(x,y)
lin.fit=lm(Y~X,df)
abline(lin.fit)
print(summary(lin.fit))
write.table(df,file="testdata.csv",row.names=FALSE,col.names=FALSE,sep=",")
