#!/usr/bin/env Rscript
randata=runif(10,-1,1)
x=c(1:10)
y=2*x+3*(randata/2)
df=data.frame(x,y)
plot(df)
lin.fit=lm(y~x,df)
abline(lin.fit)
print(summary(lin.fit))
write.table(df,file="testdata.csv",row.names=FALSE,col.names=FALSE,sep=",")
